### ISSUE TITLE
Convert scene to tetra mesh error in eval of blender2mesh

### ISSUE THREAD

**Issue by kaiobbarros** [NeuroJSON/BlenderPhotonics#10]
My name is Kaio, I'm a brazilian PhD candidate in the photobiophysics area. I'm trying to make more complex simulations than my previous with MCX, but after the instalation of BlenderPhotonics, I couldnt make the first step. When I try to convert the initial Blender cube to tetra mesh, i get the following error:

Python: Traceback (most recent call last):
File "C:\Users\Kaio BB\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderPhotonics-master\blender2mesh.py", line 203, in execute
self.func()
File "C:\Users\Kaio BB\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\BlenderPhotonics-master\blender2mesh.py", line 176, in func
oc.feval('blender2mesh',os.path.join(outputdir,'blendermesh.jmsh'), nargout=0)
File "C:\Users\Kaio BB\AppData\Roaming\Python\Python311\site-packages\oct2py\core.py", line 403, in feval
return self ._ feval(

File "C:\Users\Kaio BB\AppData\Roaming\Python\Python311\site-packages\oct2py\core.py", line 648, in_feval
raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Octave evaluation error:
error: blender2mesh: function called with too many outputs
error: called from:
blender2mesh at line -1, column -1

Aditionally, when I click the object properties, theres no optical properties like "g, ua, etc" in the custom properties. I should create then manually with the "New" option or the options should show automatically?
Can U help me in some way?

Thanks for all your contributions with optic simulations.

**Comment by fangq** [comment]
can you upgrade your iso2mesh to the github version and try again?
